framework:
    notifier:
        #chatter_transports:
        #    slack: '%env(SLACK_DSN)%'
        #    telegram: '%env(TELEGRAM_DSN)%'
        #texter_transports:
        #    twilio: '%env(TWILIO_DSN)%'
        #    nexmo: '%env(NEXMO_DSN)%'
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['chat/telegram', 'email']
            high: ['chat/telegram', 'email']
            medium: ['chat/telegram', 'email']
            low: ['chat/telegram', 'email']
        admin_recipients:
            - { email: "%env(string:default:default_admin_email:ADMIN_EMAIL)%" }
        chatter_transports:
            telegram: '%env(TELEGRAM_DSN)%'
